### ISSUE TITLE
Delete member not working

### ISSUE THREAD

**Issue by JonathanMbt** [aleksilahti/wise-nose-pwa#3]
When you click on the delete button in the member page (/members), it doesn't delete it, even if we are log in as admin.
<img width="1552" alt="Capture d’écran 2021-03-22 à 23 57 20" src="https://user-images.githubusercontent.com/63970583/112063614-5db6fe00-8b6a-11eb-9a97-75af3746c1b7.png">

**Comment by svetlanapelevina** [comment]
`
